#!/bin/bash
# clean script for masalla icon themes 
# Written by Written by Hayder Majid(Hayder Ctee) <hayder@riseup.net>
	
    rm -Rf /usr/share/icons/masalla
	rm -Rf /usr/share/icons/masalla-dark

	rm -Rf $HOME/.icons/masalla
	rm -Rf $HOME/.icons/masalla-dark

