#!/bin/bash
# install script for masalla icon themes 
# Written by Hayder Majid (Hayder Ctee) <hayder@riseup.net> (thanks to Tiheum for writting his script :-) (matthieu.james@gmail.com) )

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Icon themes will be installed in $HOME/.icons. To make them available for all users, run this script as root."
else
	echo "Icon themes will be installed in /usr/share/icons and are available for all users."
fi
read -p "Do you want to continue ? [Y]es, [N]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Wrong value: installaton aborted."; exit 1;;
esac

DIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $DIR

echo
read -p "What distributor logo would you use ? [A]rchlinux, [D]ebian, [f]edora, [F]rugalware, [G]entoo, [L]inux Mint, [O]pensuse, [M]andriva, [S]lackware, [U]buntu, [u]ruk, : " distro
distro="${input:-$distro}"
case $distro in
	[Aa]* ) distributor="archlinux";;
	[Dd]* ) distributor="debian";;
    [f]* ) distributor="fedora";;
    [F]* ) distributor="frugalware";;
    [Gg]* ) distributor="gentoo";;
    [Ll]* ) distributor="linux-mint";;
    [Oo]* ) distributor="opensuse";;
    [Mm]* ) distributor="mandriva";;
    [Ss]* ) distributor="slackware";;
    [U]* ) distributor="ubuntu";;
    [u]* ) distributor="uruk";;
    * ) echo "Wrong value: installaton aborted."; exit 1;;
esac
iconname="$distributor"
cd ./masalla/apps/scalable/ && ln -sf ./$iconname.svg distributor-logo.svg && cd ../../..
for size in 48x48 24x24 22x22; do
	cd ./masalla/apps/$size/ && ln -sf ./$iconname.svg distributor-logo.svg && cd ../../..
done

if [ -d $HOME/.icons/masalla ]
then
	echo
	read -p "An existing installation have been detected in $HOME/.icons. Remove it previously ? [Y]es, [N]o :" response
	case $response in
		[Yy]* ) rm -Rf $HOME/.icons/masalla 2>/dev/null; rm -Rf $HOME/.icons/masalla-dark 2>/dev/null;;
	    * ) ;;
	esac
fi

if [ "$UID" -eq "$ROOT_UID" ]
then
	if [ -d /usr/share/icons/masalla ]
	then
		echo
		read -p "An existing installation has been detected in /usr/share/icons. Remove it previously ? [Y]es, [N]o :" response
		case $response in
			[Yy]* ) rm -Rf /usr/share/icons/masalla 2>/dev/null; rm -Rf /usr/share/icons/masalla-dark 2>/dev/null;;
		    * ) ;;
		esac
		echo
	fi
	./CLEAN
	cp -R ./masalla /usr/share/icons/
	cp -R ./masalla-dark /usr/share/icons/

	install_dir=/usr/share/icons/
else
	./CLEAN
	cp -R ./masalla $HOME/.icons/
	cp -R ./masalla-dark $HOME/.icons/

	install_dir=$HOME/.icons/
fi

echo
echo "Installation complete. Enjoy !"
exit 0
