#!/bin/bash
# Uninstall script for masalla icon themes 
# Written by Written by Hayder Majid(Hayder Ctee) <hayder@riseup.net> (thanks to Tiheum for writting his script :-) (matthieu.james@gmail.com) )

ROOT_UID=0
if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "masalla icon themes installed in $HOME/.icons will be removed."
else
	echo "masalla icon themes installed in /usr/share/icons will be removed. According to your choices during installation, some default icons will be restored."
fi
read -p "Do you want to continue ? [Y]es, [N]o : " response
case $response in
	[Yy]* ) ;;
    [Nn]* ) exit 99;;
    * ) echo "Wrong value: uninstall aborted."; exit 1;;
esac

if [ "$UID" -eq "$ROOT_UID" ]
then
	rm -Rf /usr/share/icons/masalla
	rm -Rf /usr/share/icons/masalla-dark
else
	rm -Rf $HOME/.icons/masalla
	rm -Rf $HOME/.icons/masalla-dark
fi

echo "Uninstall complete. Bey :-("
exit 0
